#!/bin/bash
image="$1"

mkfifo fifo # &> /dev/null
[[ -r fifo && -w fifo && -p fifo ]] || { echo "fifo fail"; exit 1; } 

< fifo qemu-system-x86_64 -kernel bzImage -append "rdinit=/init console=ttyS0,9600n8" -initrd initramfs.cpio.gz  -net none -m 64 -serial mon:stdio -nographic "$image"| \
	while read f
	do
		echo "$f" >&2
		[[ $f == "Freeing unused kernel memory"* ]] && { 
			sleep 3
			echo $'\x01c'
			echo 'savevm start'
			echo 'quit'
		}
	done > fifo

rm -f fifo

