#!/bin/bash
hostname bunnies
mount -t proc none /proc 

stty -echo
export PS1=""
export PS2="Missing terminating quote, bracket or keyword"
export PROMPT_COMMAND='[[ $LOLFF ]] && echo o > /proc/sysrq-trigger; LOLFF=42;'
export HOME=/root
cd "$HOME"

mknod /dev/null c 1 3
mknod /dev/full c 1 7
rm /init


read RANDOM
read date
date -s "1970-01-01 + $date seconds" &> /dev/null

unset date
/bin/bash -l
echo "(shell exited with $?)"
echo o > /proc/sysrq-trigger
sleep 10
